# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']


MACHINES = {
  :PAM => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
		
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "512"]
		end
                
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	  
		useradd admin && useradd user
		echo "1234" | passwd --stdin admin && echo "1234" | passwd --stdin user
		sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
		systemctl restart sshd
		echo '*;*;!admin;!Wd0000-2400' >> /etc/security/time.conf
		sed -i '7i\ account required pam_time.so' /etc/pam.d/sshd
		echo 'admin ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 
  	  SHELL

      end
  end
end

